name: publish docker image to docker hub

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobes:
  build:
    run-on: ubuntu-latest

    steps:
      -users: action/checkout@v3
      -name: login to docker hub
       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
       with:
        username: ${{secrets.DOCKER_KEY}}
        # password: ${{secrets.DOCKER_PASS}}

      -name: build the docker iamge
       run: docker build . --file Dockerfile --tag ${{secters.DOCKER_KEY}}/flask-jenkins-project

      -name: docker push
       run:   docker push ${{sectets.DOCKER_KEY}}/flask-jenkins-project

 
