

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
      DOCKER_USER:${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD:${{secrets.DOCKER_PASSWORD}}
     run:| 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
         - name:build the docker iamge
          run:docker build . --file Dockerfile --tag danialkarim807/flask-jenkins-project

          - name:docker push
           run:docker push ${{sectets.DOCKER_KEY}}/flask-jenkins-project

 
